- name: compassインストール
  gem: name=compass user_install=False executable={{ ANSIBLE_YEOMAN_USER_HOME }}/{{ ANSIBLE_YEOMAN_GEM_PATH }}
  sudo: yes

- name: node path check
  shell: "[ -f /usr/bin/node ] && echo 'Found' || echo ''" 
  register: result
  sudo: yes

- name: yeoman fix
  file: src={{ ANSIBLE_YEOMAN_USER_HOME }}/{{ ANSIBLE_YEOMAN_NODE_PATH }}/node path=/usr/bin/node  state=link follow=yes
  when: (not result.stdout)  
  sudo: yes

- name: yoのためにホームディレクトリにg+rwx(rootユーザ実行時のfix)
  file: path={{ ANSIBLE_YEOMAN_USER_HOME }} mode=g+rwx
  when: (ANSIBLE_YEOMAN_USER == "root")
  sudo: yes

- name: yeomanインストール
  npm: name={{item.pkg}} global=yes executable={{ ANSIBLE_YEOMAN_USER_HOME }}/{{ ANSIBLE_YEOMAN_NODE_PATH }}/npm
  with_items:
    - pkg: yo
    - pkg: grunt-cli
    - pkg: bower
  sudo: yes

- name: generatorインストール
  npm: name={{item}} global=yes executable={{ ANSIBLE_YEOMAN_USER_HOME }}/{{ ANSIBLE_YEOMAN_NODE_PATH }}/npm
  with_items: generators
  sudo: yes
